{
  "parameters": {
    "api-version": "2020-10-31",
    "id": "mySourceTwin",
    "relationshipId": "myRelationshipId",
    "relationship": {
      "$targetId": "myTargetTwin",
      "$relationshipName": "myRelationship",
      "relationshipProperty1": 1,
      "relationshipProperty2": "some value"
    }
  },
  "responses": {
    "200": {
      "body": {
        "$relationshipId": "myRelationshipId",
        "$sourceId": "mySourceTwin",
        "$targetId": "myTargetTwin",
        "$relationshipName": "myRelationship",
        "relationshipProperty1": 1,
        "relationshipProperty2": "some value",
        "$etag": "W/\"1553dbf5-0052-4be8-bea8-46269075b503\""
      }
    },
    "400": {
      "body": {
        "error": {
          "code": "InvalidRelationship",
          "message": "Twin relationship does not align with the model."
        }
      }
    },
    "404": {
      "body": {
        "error": {
          "code": "DigitalTwinNotFound",
          "message": "Please verify that the twin id is valid and ensure that the twin is not deleted."
        }
      }
    },
    "409": {
      "body": {
        "error": {
          "code": "RelationshipAlreadyExists",
          "message": "Relationship with id 'rel-1' already exists on twin 'dt-1'."
        }
      }
    },
    "412": {
      "body": {
        "error": {
          "code": "PreconditionFailed",
          "message": "If-None-Match: * header was specified but a relationship with the id 'rel-1' was found."
        }
      }
    }
  }
}
