{
  "parameters": {
    "api-version": "2021-02-01-preview",
    "subscriptionId": "4385cf00-2d3a-425a-832f-f4285b1c9dce",
    "resourceGroupName": "GroupForEdgeAutomation",
    "deviceName": "testedgedevice",
    "name": "159a00c7-8543-4343-9435-263ac87df3bb",
    "x-ms-client-request-id": [
      "a93b39a3-1ff4-42b8-a56f-43368d47e37a"
    ],
    "accept-language": [
      "en-US"
    ]
  },
  "responses": {
    "200": {
      "body": {
        "properties": {
          "title": "Could not scan for updates. Error message : 'An internal error has occurred. Please contact Microsoft Support.'.",
          "alertType": "UpdateScanFailedEvent",
          "appearedAtDateTime": "2018-12-18T02:18:51.4270267Z",
          "recommendation": "Resolve the error : An internal error has occurred. Please contact Microsoft Support.",
          "severity": "Critical",
          "errorDetails": {
            "errorCode": "",
            "errorMessage": "",
            "occurrences": 1
          },
          "detailedInformation": {}
        },
        "id": "/subscriptions/4385cf00-2d3a-425a-832f-f4285b1c9dce/resourceGroups/GroupForEdgeAutomation/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/testedgedevice/alerts/159a00c7-8543-4343-9435-263ac87df3bb",
        "name": "159a00c7-8543-4343-9435-263ac87df3bb",
        "type": "dataBoxEdgeDevices/alerts"
      }
    }
  }
}
