{
  "parameters": {
    "api-version": "2016-08-10",
    "jobName": "2653c648-fc72-4316-86f3-fdf8eaa0066b",
    "resourceName": "vault1",
    "resourceGroupName": "resourceGroupPS1",
    "subscriptionId": "c183865e-6077-46f2-a3b1-deb0f4f4650a"
  },
  "responses": {
    "200": {
      "body": {
        "id": "/Subscriptions/c183865e-6077-46f2-a3b1-deb0f4f4650a/resourceGroups/resourceGroupPS1/providers/Microsoft.RecoveryServices/vaults/vault1/replicationJobs/2653c648-fc72-4316-86f3-fdf8eaa0066b",
        "name": "2653c648-fc72-4316-86f3-fdf8eaa0066b",
        "properties": {
          "activityId": "bfbbf6dd-9cbb-4cbc-98a6-faecc8891579 ActivityId: 07cc35ca-b63f-4e42-83c9-81ae0191c322",
          "scenarioName": "PlannedFailover",
          "friendlyName": "Planned failover",
          "state": "Cancelling",
          "stateDescription": "Cancelling",
          "tasks": [
            {
              "taskId": "PlannedFailoverPreflightChecksTask",
              "name": "VmPfoPrerequisitesCheck",
              "startTime": "2017-05-03T06:16:08.1390467Z",
              "endTime": "2017-05-03T06:16:56.4671827Z",
              "allowedActions": [],
              "friendlyName": "Prerequisites check for planned failover",
              "state": "Cancelled",
              "stateDescription": "Cancelled",
              "taskType": "TaskDetails",
              "customDetails": {
                "instanceType": "TaskDetails"
              },
              "errors": []
            },
            {
              "taskId": "ShutdownVmOnPrimary",
              "name": "VmShutdownVmOnPrimary",
              "startTime": "0001-01-01T00:00:00",
              "endTime": "0001-01-01T00:00:00",
              "allowedActions": [],
              "friendlyName": "Shut down the virtual machine",
              "state": "NotStarted",
              "stateDescription": "NotStarted",
              "taskType": "TaskDetails",
              "customDetails": {
                "instanceType": "TaskDetails"
              },
              "errors": []
            },
            {
              "taskId": "PrepareForFailoverTask",
              "name": "VmPrepareForFailover",
              "startTime": "0001-01-01T00:00:00",
              "endTime": "0001-01-01T00:00:00",
              "allowedActions": [],
              "friendlyName": "Preparing for failover",
              "state": "NotStarted",
              "stateDescription": "NotStarted",
              "taskType": "TaskDetails",
              "customDetails": {
                "instanceType": "TaskDetails"
              },
              "errors": []
            },
            {
              "taskId": "FailoverTask",
              "name": "VmFailover",
              "startTime": "0001-01-01T00:00:00",
              "endTime": "0001-01-01T00:00:00",
              "allowedActions": [],
              "friendlyName": "Start failover",
              "state": "NotStarted",
              "stateDescription": "NotStarted",
              "taskType": "TaskDetails",
              "customDetails": {
                "instanceType": "TaskDetails"
              },
              "errors": []
            },
            {
              "taskId": "StartVmOnSecondary",
              "name": "VmFoStartVmOnSecondary",
              "startTime": "0001-01-01T00:00:00",
              "endTime": "0001-01-01T00:00:00",
              "allowedActions": [],
              "friendlyName": "Start the replica virtual machine",
              "state": "NotStarted",
              "stateDescription": "NotStarted",
              "taskType": "TaskDetails",
              "customDetails": {
                "instanceType": "TaskDetails"
              },
              "errors": []
            }
          ],
          "errors": [
            {
              "serviceErrorDetails": {
                "code": "538",
                "message": "The job was canceled.",
                "possibleCauses": "If the job was canceled because it was running for a long time, check whether there's a related job currently in progress. If there is one wait for it to complete and retry the operation. Alternatively, check whether the job's waiting for a server task to complete, and the server isn't responding. If this occurs, check the server connection.",
                "recommendedAction": "If there is a related job currently in progress, wait for the job to complete and then retry the operation.",
                "activityId": "bfbbf6dd-9cbb-4cbc-98a6-faecc8891579 ActivityId: 07cc35ca-b63f-4e42-83c9-81ae0191c322"
              },
              "providerErrorDetails": {
                "errorCode": 0,
                "errorId": "9336cc9a-b23f-40c1-b8b2-e28830894408",
                "possibleCauses": "",
                "recommendedAction": ""
              },
              "errorLevel": "Error",
              "creationTime": "2017-05-03T06:16:50.5785642Z"
            }
          ],
          "startTime": "2017-05-03T06:16:06.3235186Z",
          "allowedActions": [],
          "targetObjectId": "f8491e4f-817a-40dd-a90c-af773978c75b",
          "targetObjectName": "vm1",
          "targetInstanceType": "ProtectionEntity",
          "customDetails": {
            "instanceType": "AsrJobDetails",
            "affectedObjectDetails": {
              "PrimaryVmId": "f8491e4f-817a-40dd-a90c-af773978c75b",
              "PrimaryVmName": "vm1",
              "RecoveryVmId": "",
              "RecoveryVmName": "vm1",
              "ProtectionProfileId": "af095a1e-1f1b-5365-87c9-99162ebcfaf0",
              "PrimaryCloudId": "cloud_6d224fc6-f326-5d35-96de-fbf51efb3179",
              "PrimaryCloudName": "cloud1",
              "RecoveryCloudId": "d38048d4-b460-4791-8ece-108395ee8478",
              "RecoveryCloudName": "Microsoft Azure",
              "PrimaryVmmId": "6d224fc6-f326-5d35-96de-fbf51efb3179",
              "PrimaryVmmName": "cloud1",
              "RecoveryVmmId": "21a9403c-6ec1-44f2-b744-b4e50b792387",
              "RecoveryVmmName": "Microsoft Azure",
              "PrimaryFabricProviderId": "HyperVSite",
              "RecoveryFabricProviderId": "Azure"
            }
          }
        },
        "status": "Cancelling",
        "error": {
          "code": "538",
          "message": "The job was canceled."
        },
        "startTime": "2017-05-03T06:16:06.3235186Z"
      }
    },
    "202": {
    }
  }
}
